### ISSUE TITLE
User manaul of the Capacitive_Fingerprint_Sensor_SKU_SEN0348

### ISSUE THREAD

**Issue by horsemann07** [DFRobot/DFRobot_ID809#3]
Hello, 

I want to use the Capacitive_Fingerprint_Sensor_SKU_SEN0348 with esp32  with esp-idf.
I was thinking to write the code for that, but I did not found and manual or document for this sensor.

Can anyone help where should I get the manual or documents ??

**Comment by byamasu-patrick** [comment]
Hello,

I am also facing the same problem I cannot manage to access the capacitive fingerpring sensor using begin function. Anyone to suggest where to get the manual on how to setup Rx and Tx pin woth Arduino UNO?

**Comment by qsjhyy** [comment]
https://wiki.dfrobot.com/search/ID809

**Comment by byamasu-patrick** [comment]
Thank you so very much @qsjhyy
